### ISSUE TITLE
Meetings/Notes

### ISSUE THREAD

**Issue by alisonmyers** [saud-learning-services/panopto-video-analytics#5]
## 2020-09-22

- [ ] notes added
- [ ] label as meeting-minutes
- [ ] link to project (as appropriate)
- [ ] issues created from meeting -> "project-todos" where appropriate

### Notes
- Instructors interested in video analytics, need to be able to provide this as a service
- Panopto is already part of workflow, so makes sense to start here
- Will eventually 
- [Panopto REST API](https://demo.hosted.panopto.com/Panopto/Api/Docs/index.html)
- [Panopto SOAP API](https://support.panopto.com/resource/APIDocumentation/Help/html/c40c21c6-dc7a-d822-8c99-b276ee8337c2.htm)
- goal: AWS integration (don't want this to live in W/)

### TODOs (can become issues as needed)
- [ ] create documentation of current data - what it is, what it means
- [ ] create documentation of how to get data - manually
- [ ] create documentation of how to get data - possibilities using api
